/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as InvestigatorRouteImport } from './routes/investigator'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultNewRouteImport } from './routes/vault.new'
import { Route as VaultSlugRouteImport } from './routes/vault.$slug'
import { Route as TheorySlugRouteImport } from './routes/theory.$slug'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigatorRoute = InvestigatorRouteImport.update({
  id: '/investigator',
  path: '/investigator',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultNewRoute = VaultNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VaultRoute,
} as any)
const VaultSlugRoute = VaultSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VaultRoute,
} as any)
const TheorySlugRoute = TheorySlugRouteImport.update({
  id: '/theory/$slug',
  path: '/theory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/investigator': typeof InvestigatorRoute
  '/sources': typeof SourcesRoute
  '/vault': typeof VaultRouteWithChildren
  '/theory/$slug': typeof TheorySlugRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/vault/new': typeof VaultNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/investigator': typeof InvestigatorRoute
  '/sources': typeof SourcesRoute
  '/vault': typeof VaultRouteWithChildren
  '/theory/$slug': typeof TheorySlugRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/vault/new': typeof VaultNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/investigator': typeof InvestigatorRoute
  '/sources': typeof SourcesRoute
  '/vault': typeof VaultRouteWithChildren
  '/theory/$slug': typeof TheorySlugRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/vault/new': typeof VaultNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/explorer'
    | '/graph'
    | '/investigator'
    | '/sources'
    | '/vault'
    | '/theory/$slug'
    | '/vault/$slug'
    | '/vault/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/explorer'
    | '/graph'
    | '/investigator'
    | '/sources'
    | '/vault'
    | '/theory/$slug'
    | '/vault/$slug'
    | '/vault/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/explorer'
    | '/graph'
    | '/investigator'
    | '/sources'
    | '/vault'
    | '/theory/$slug'
    | '/vault/$slug'
    | '/vault/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ExplorerRoute: typeof ExplorerRoute
  GraphRoute: typeof GraphRoute
  InvestigatorRoute: typeof InvestigatorRoute
  SourcesRoute: typeof SourcesRoute
  VaultRoute: typeof VaultRouteWithChildren
  TheorySlugRoute: typeof TheorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigator': {
      id: '/investigator'
      path: '/investigator'
      fullPath: '/investigator'
      preLoaderRoute: typeof InvestigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/new': {
      id: '/vault/new'
      path: '/new'
      fullPath: '/vault/new'
      preLoaderRoute: typeof VaultNewRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/$slug': {
      id: '/vault/$slug'
      path: '/$slug'
      fullPath: '/vault/$slug'
      preLoaderRoute: typeof VaultSlugRouteImport
      parentRoute: typeof VaultRoute
    }
    '/theory/$slug': {
      id: '/theory/$slug'
      path: '/theory/$slug'
      fullPath: '/theory/$slug'
      preLoaderRoute: typeof TheorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VaultRouteChildren {
  VaultSlugRoute: typeof VaultSlugRoute
  VaultNewRoute: typeof VaultNewRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultSlugRoute: VaultSlugRoute,
  VaultNewRoute: VaultNewRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ExplorerRoute: ExplorerRoute,
  GraphRoute: GraphRoute,
  InvestigatorRoute: InvestigatorRoute,
  SourcesRoute: SourcesRoute,
  VaultRoute: VaultRouteWithChildren,
  TheorySlugRoute: TheorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
