/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as InvestigatorRouteImport } from './routes/investigator'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheorySlugRouteImport } from './routes/theory.$slug'
import { Route as VaultNewRouteImport } from './routes/vault.new'
import { Route as VaultSlugRouteImport } from './routes/vault.$slug'

const VaultRoute = VaultRouteImport.update({ id: '/vault', path: '/vault', getParentRoute: () => rootRouteImport } as any)
const SourcesRoute = SourcesRouteImport.update({ id: '/sources', path: '/sources', getParentRoute: () => rootRouteImport } as any)
const InvestigatorRoute = InvestigatorRouteImport.update({ id: '/investigator', path: '/investigator', getParentRoute: () => rootRouteImport } as any)
const GraphRoute = GraphRouteImport.update({ id: '/graph', path: '/graph', getParentRoute: () => rootRouteImport } as any)
const ExplorerRoute = ExplorerRouteImport.update({ id: '/explorer', path: '/explorer', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const TheorySlugRoute = TheorySlugRouteImport.update({ id: '/theory/$slug', path: '/theory/$slug', getParentRoute: () => rootRouteImport } as any)
const VaultNewRoute = VaultNewRouteImport.update({ id: '/vault/new', path: '/vault/new', getParentRoute: () => rootRouteImport } as any)
const VaultSlugRoute = VaultSlugRouteImport.update({ id: '/vault/$slug', path: '/vault/$slug', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/investigator': typeof InvestigatorRoute
  '/sources': typeof SourcesRoute
  '/vault': typeof VaultRoute
  '/theory/$slug': typeof TheorySlugRoute
  '/vault/new': typeof VaultNewRoute
  '/vault/$slug': typeof VaultSlugRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById extends FileRoutesByFullPath {
  __root__: typeof rootRouteImport
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/auth' | '/explorer' | '/graph' | '/investigator' | '/sources' | '/vault' | '/theory/$slug' | '/vault/new' | '/vault/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auth' | '/explorer' | '/graph' | '/investigator' | '/sources' | '/vault' | '/theory/$slug' | '/vault/new' | '/vault/$slug'
  id: '__root__' | '/' | '/admin' | '/auth' | '/explorer' | '/graph' | '/investigator' | '/sources' | '/vault' | '/theory/$slug' | '/vault/new' | '/vault/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ExplorerRoute: typeof ExplorerRoute
  GraphRoute: typeof GraphRoute
  InvestigatorRoute: typeof InvestigatorRoute
  SourcesRoute: typeof SourcesRoute
  VaultRoute: typeof VaultRoute
  TheorySlugRoute: typeof TheorySlugRoute
  VaultNewRoute: typeof VaultNewRoute
  VaultSlugRoute: typeof VaultSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': { id: '/vault'; path: '/vault'; fullPath: '/vault'; preLoaderRoute: typeof VaultRouteImport; parentRoute: typeof rootRouteImport }
    '/sources': { id: '/sources'; path: '/sources'; fullPath: '/sources'; preLoaderRoute: typeof SourcesRouteImport; parentRoute: typeof rootRouteImport }
    '/investigator': { id: '/investigator'; path: '/investigator'; fullPath: '/investigator'; preLoaderRoute: typeof InvestigatorRouteImport; parentRoute: typeof rootRouteImport }
    '/graph': { id: '/graph'; path: '/graph'; fullPath: '/graph'; preLoaderRoute: typeof GraphRouteImport; parentRoute: typeof rootRouteImport }
    '/explorer': { id: '/explorer'; path: '/explorer'; fullPath: '/explorer'; preLoaderRoute: typeof ExplorerRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/theory/$slug': { id: '/theory/$slug'; path: '/theory/$slug'; fullPath: '/theory/$slug'; preLoaderRoute: typeof TheorySlugRouteImport; parentRoute: typeof rootRouteImport }
    '/vault/new': { id: '/vault/new'; path: '/vault/new'; fullPath: '/vault/new'; preLoaderRoute: typeof VaultNewRouteImport; parentRoute: typeof rootRouteImport }
    '/vault/$slug': { id: '/vault/$slug'; path: '/vault/$slug'; fullPath: '/vault/$slug'; preLoaderRoute: typeof VaultSlugRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AdminRoute, AuthRoute, ExplorerRoute, GraphRoute, InvestigatorRoute, SourcesRoute, VaultRoute, TheorySlugRoute, VaultNewRoute, VaultSlugRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
